/*
 *
 * $Id: SVGGoban.java 15 2003-03-15 23:25:52Z cgawron $
 *
 * © 2001 Christian Gawron. All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 */

package de.cgawron.go.render.svg;

import java.awt.BasicStroke;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.*;
import java.awt.font.*;
import java.awt.geom.*;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.logging.Logger;

import org.apache.batik.dom.GenericDOMImplementation;
import org.apache.batik.svggen.SVGGraphics2D;
import org.apache.batik.svggen.SVGGeneratorContext;

import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;

public class SVGGoban
{
    private static Logger logger = Logger.getLogger(SVGGoban.class.getName());
    private GobanRenderer renderer = new SimpleGobanRenderer();

    private Graphics2D scaleGraphics(Graphics2D g, GobanModel model)
    {
        if (g == null)
            return null;

        RenderingHints hints = new RenderingHints(null);
        hints.put(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g.addRenderingHints(hints);

        double min = 400;
        int boardSize = model.getBoardSize();

        g.scale(min / boardSize, min / boardSize);

        logger.info("scaleGraphics: " + min + ", " + boardSize);
        g.setStroke(new BasicStroke(0.02f));

        return g;
    }

    public void paint(Graphics2D g2d)
    {
        MarkupModel model = new SimpleMarkupModel((short)19);
        model.move((short)3, (short)3, BoardType.Black);
        model.setMarkup((short)3, (short)3, new MarkupModel.Move(BoardType.Black, 9));
        renderer.paint(scaleGraphics(g2d, model), model);
    }

    public static void main(String[] args) throws IOException
    {

        // Get a DOMImplementation
        DOMImplementation domImpl = GenericDOMImplementation.getDOMImplementation();

        // Create an instance of org.w3c.dom.Document
        Document document = domImpl.createDocument(null, "svg", null);

        // Create an instance of the SVG Generator
	SVGGeneratorContext ctx = SVGGeneratorContext.createDefault(document);
	ctx.setComment("Generated by FooApplication with Batik SVG Generator");
	SVGGraphics2D svgGenerator = new SVGGraphics2D(ctx, false);
	
        // Ask the test to render into the SVG Graphics2D implementation
        SVGGoban test = new SVGGoban();
        test.paint(svgGenerator);

        // Finally, stream out SVG to the standard output using UTF-8
        // character to byte encoding
        boolean useCSS = true; // we want to use CSS style attribute
        Writer out = new OutputStreamWriter(System.out, "UTF-8");
        svgGenerator.stream(out, useCSS);
    }
}
